name: flutter_lints_plus
description: Recommended lints for Flutter apps, packages, and plugins to encourage good coding practices.
repository: https://github.com/ronjb/flutter_lints_plus
homepage: https://github.com/ronjb/flutter_lints_plus
version: 2.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter_lints: ^2.0.1
